## Deliverable 2. Create a Customer Travel Destinations Map.

In [29]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [31]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_data/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Current Discription
0,0,Busselton,-33.6500,115.3333,62.64,77,100,16.58,AU,overcast clouds
1,1,Thompson,55.7435,-97.8558,33.96,93,100,10.36,CA,overcast clouds
2,2,Norman Wells,65.2820,-126.8329,14.77,87,100,13.82,CA,overcast clouds
3,3,Shetpe,44.1667,52.1167,51.93,67,34,3.80,KZ,scattered clouds
4,4,Bluff,-46.6000,168.3333,58.10,73,7,23.85,NZ,clear sky

In [15]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [16]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Current Discription
5,5,Guanica,17.9716,-66.9080,78.06,78,51,9.24,PR,broken clouds
6,6,Vaini,-21.2000,-175.2000,84.36,74,20,8.05,TO,few clouds
10,10,Pilar,-9.5972,-35.9567,75.13,85,72,2.15,BR,broken clouds
13,13,Acapulco,16.8634,-99.8901,80.42,78,40,8.05,MX,scattered clouds
14,14,Kapaa,22.0752,-159.3190,82.38,76,20,12.66,US,few clouds
15,15,Rikitea,-23.1203,-134.9692,79.09,71,7,17.58,PF,clear sky
16,16,Morant Bay,17.8815,-76.4093,76.71,79,95,5.41,JM,overcast clouds
19,19,Hobart,-42.8794,147.3294,78.03,48,75,10.36,AU,broken clouds
22,22,Minuri,16.5350,121.8574,78.67,86,97,1.48,PH,overcast clouds
31,31,Kavaratti,10.5669,72.6420,83.05,75,100,6.31,IN,light rain

In [17]:
# 4a. Determine if there are any empty rows.
city_data_df.isnull().count()

City_ID                686
City                   686
Lat                    686
Lng                    686
Max Temp               686
Humidity               686
Cloudiness             686
Wind Speed             686
Country                686
Current Discription    686
dtype: int64

In [18]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df =city_data_df.dropna()
clean_df.head(50)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Current Discription
0,0,Busselton,-33.6500,115.3333,62.64,77,100,16.58,AU,overcast clouds
1,1,Thompson,55.7435,-97.8558,33.96,93,100,10.36,CA,overcast clouds
2,2,Norman Wells,65.2820,-126.8329,14.77,87,100,13.82,CA,overcast clouds
3,3,Shetpe,44.1667,52.1167,51.93,67,34,3.80,KZ,scattered clouds
4,4,Bluff,-46.6000,168.3333,58.10,73,7,23.85,NZ,clear sky
5,5,Guanica,17.9716,-66.9080,78.06,78,51,9.24,PR,broken clouds
6,6,Vaini,-21.2000,-175.2000,84.36,74,20,8.05,TO,few clouds
7,7,Ushuaia,-54.8000,-68.3000,47.86,71,75,16.11,AR,broken clouds
8,8,Port Alfred,-33.5906,26.8910,62.19,96,100,7.00,ZA,overcast clouds
9,9,Banyo,6.7500,11.8167,67.48,84,100,5.08,CM,overcast clouds
10,10,Pilar,-9.5972,-35.9567,75.13,85,72,2.15,BR,broken clouds
11,11,Yellowknife,62.4560,-114.3525,27.41,69,100,21.00,CA,overcast clouds
12,12,Dikson,73.5069,80.5464,7.25,97,97,6.20,RU,overcast clouds
13,13,Acapulco,16.8634,-99.8901,80.42,78,40,8.05,MX,scattered clouds
14,14,Kapaa,22.0752,-159.3190,82.38,76,20,12.66,US,few clouds
15,15,Rikitea,-23.1203,-134.9692,79.09,71,7,17.58,PF,clear sky
16,16,Morant Bay,17.8815,-76.4093,76.71,79,95,5.41,JM,overcast clouds
17,17,Mataura,-46.1927,168.8643,61.20,51,7,4.79,NZ,clear sky
18,18,Rezekne,56.5000,27.3167,32.52,75,0,11.23,LV,clear sky
19,19,Hobart,-42.8794,147.3294,78.03,48,75,10.36,AU,broken clouds
20,20,Swellendam,-34.0226,20.4417,57.42,86,0,3.96,ZA,clear sky
21,21,La Ronge,55.1001,-105.2842,36.95,86,81,11.48,CA,broken clouds
22,22,Minuri,16.5350,121.8574,78.67,86,97,1.48,PH,overcast clouds
23,23,Albany,42.6001,-73.9662,42.64,86,11,4.97,US,few clouds
24,24,Beringovskiy,63.0500,179.3167,34.09,83,77,24.40,RU,broken clouds
25,25,Fortuna,40.5982,-124.1573,51.93,71,40,26.46,US,scattered clouds
26,26,Afsin,38.2477,36.9140,50.99,72,97,4.94,TR,overcast clouds
27,27,Hasaki,35.7333,140.8333,73.29,66,0,4.65,JP,clear sky
28,28,Sinegorye,62.0788,150.4770,0.59,85,100,6.17,RU,overcast clouds
29,29,Coihaique,-45.5752,-72.0662,51.75,66,75,4.61,CL,broken clouds
30,30,Ostrovnoy,68.0531,39.5131,29.53,86,13,13.62,RU,few clouds
31,31,Kavaratti,10.5669,72.6420,83.05,75,100,6.31,IN,light rain
32,32,Carutapera,-1.1950,-46.0200,75.18,95,100,3.87,BR,overcast clouds
33,33,Pacific Grove,36.6177,-121.9166,73.45,68,75,11.99,US,broken clouds
34,34,Avarua,-21.2078,-159.7750,84.25,79,40,6.91,CK,scattered clouds
35,35,Belaya Gora,68.5333,146.4167,-1.17,87,100,5.59,RU,overcast clouds
36,36,Rawson,-43.3002,-65.1023,61.09,94,40,11.50,AR,scattered clouds
37,37,Butaritari,3.0707,172.7902,80.71,80,95,13.53,KI,light rain
38,38,Chokurdakh,70.6333,147.9167,-5.75,94,98,4.27,RU,overcast clouds
39,39,Moose Factory,51.2585,-80.6094,26.58,93,100,5.75,CA,overcast clouds
40,40,Hithadhoo,-0.6000,73.0833,83.14,74,26,10.60,MV,scattered clouds
41,41,Meulaboh,4.1363,96.1285,78.66,86,51,2.42,ID,broken clouds
42,42,Mabaruma,8.2000,-59.7833,73.65,92,33,3.65,GY,scattered clouds
43,43,Yulara,-25.2406,130.9889,84.04,17,0,9.22,AU,clear sky
44,44,Kurkino,53.4257,38.6582,47.77,70,100,15.84,RU,overcast clouds
45,45,Baykit,61.6700,96.3700,24.75,89,100,1.30,RU,overcast clouds
46,46,Hella,67.2000,14.4333,38.05,87,40,9.22,NO,scattered clouds
47,47,Arraial Do Cabo,-22.9661,-42.0278,76.53,90,96,10.78,BR,overcast clouds
48,48,Atuona,-9.8000,-139.0333,79.52,73,13,19.95,PF,few clouds
49,49,Cape Town,-33.9258,18.4232,62.11,74,0,9.22,ZA,clear sky

In [19]:
clean_df.isnull().sum()

City_ID                0
City                   0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Country                0
Current Discription    0
dtype: int64

In [20]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Discription", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Discription,Lat,Lng,Hotel Name
0,Busselton,AU,62.64,overcast clouds,-33.6500,115.3333,
1,Thompson,CA,33.96,overcast clouds,55.7435,-97.8558,
2,Norman Wells,CA,14.77,overcast clouds,65.2820,-126.8329,
3,Shetpe,KZ,51.93,scattered clouds,44.1667,52.1167,
4,Bluff,NZ,58.10,clear sky,-46.6000,168.3333,
5,Guanica,PR,78.06,broken clouds,17.9716,-66.9080,
6,Vaini,TO,84.36,few clouds,-21.2000,-175.2000,
7,Ushuaia,AR,47.86,broken clouds,-54.8000,-68.3000,
8,Port Alfred,ZA,62.19,overcast clouds,-33.5906,26.8910,
9,Banyo,CM,67.48,overcast clouds,6.7500,11.8167,

In [21]:
# Dependencies and Setup
import requests
import gmaps

# Import API key
from config import g_key

In [22]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key    
}

# 6b. Iterate through the hotel DataFrame.

for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"

    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    

    # 6e. Make request and retrieve the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
 
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try :
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]

  
    except(IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [23]:
# 7. Drop the rows where there is no Hotel Name.

hotel_df['Hotel Name'].replace('',np.nan,inplace= True)

hotel_df.dropna(subset=['Hotel Name'],inplace =True)

In [24]:
hotel_df.head(10)

,City,Country,Max Temp,Current Discription,Lat,Lng,Hotel Name
0,Busselton,AU,62.64,overcast clouds,-33.6500,115.3333,Observatory Guest House
1,Thompson,CA,33.96,overcast clouds,55.7435,-97.8558,Burntwood Hotel
2,Norman Wells,CA,14.77,overcast clouds,65.2820,-126.8329,Heritage Hotel
3,Shetpe,KZ,51.93,scattered clouds,44.1667,52.1167,Rtsm Shetpe Analog
4,Bluff,NZ,58.10,clear sky,-46.6000,168.3333,Bluff Homestead - Guesthouse & Campervan Park
5,Guanica,PR,78.06,broken clouds,17.9716,-66.9080,Copamarina Beach Resort & Spa
6,Vaini,TO,84.36,few clouds,-21.2000,-175.2000,Keleti Beach Resort
7,Ushuaia,AR,47.86,broken clouds,-54.8000,-68.3000,Albatross Hotel
8,Port Alfred,ZA,62.19,overcast clouds,-33.5906,26.8910,The Halyards Hotel
9,Banyo,CM,67.48,overcast clouds,6.7500,11.8167,Motel JOMBA

In [25]:
# 8a. Create the output File (CSV)

output_data_file = "../Vacation_Search/WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [26]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Discription/dt><dd>{Current Discription} and {Max Temp} °F</dd>
</dl>
"""


# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [28]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure()
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(47.6,-52.7), zoom_level=3.5)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))